version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 16 # or python/java
    commands:
      - echo Installing dependencies
      - npm install
  build:
    commands:
      - echo Build started
      - npm run build  # or your build command
artifacts:
  files:
    - '**/*'
